name: CI - Create Library

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-action:
    name: test-action/create-library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      ## create a library
      - name: create-library-1
        uses: ./create-library
        with:
            license: ${{ secrets.PROGRESS_CFG_LICENSE }}
            working-directory: create-library/test/test1
      - name: test-1
        shell: bash
        working-directory: create-library/test/test1
        run: |
          find . -name "*.pl"
          PL_COUNT=$(find . -name "*.pl" | wc -l)
          [ "$PL_COUNT" -eq 2 ] || (echo "::error::Expected pl count=1 but got $PL_COUNT" && exit 1)

      - name: pre-merge-validation
        shell: bash
        run: ./.github/workflows/pre_merge_validation.sh create-library
