name: CI - Database Create

on:
  workflow_call

permissions:
  contents: read

jobs:
  test-action:
    name: test-action/database-create
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      ## create a database
      - name: database-create-1
        uses: ./database-create
        with:
            license: ${{ secrets.PROGRESS_CFG_LICENSE }}
            working-directory: load-schema/test/test1
            db-name: myDb
      - name: load-schema-1
        uses: ./load-schema
        with:
            working-directory: load-schema/test/test1
            db-name: myDb
            schema-file: schema.df
      - name: test-1A
        shell: bash
        working-directory: database-create/test/test1
        run: |
          [ -f "db/myDb.db" ] || (echo "::error::Expected database file db/myDb.db but it was not found" && exit 1)
      - name: test-1B
        uses: ./run
        with:
          startup_procedure: load-schema/test/test1/verify.p
          additional-parameter: -db load-schema/test/test1/db/myDb -singleUser


      - name: pre-merge-validation
        shell: bash
        run: ./.github/workflows/pre_merge_validation.sh database-create
