name: CI - Run

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-action:
    name: test-action/run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      ## simple test
      - name: run-1
        uses: ./run
        with:
          license: ${{ secrets.PROGRESS_CFG_LICENSE }}
          startup-procedure: run/test/test_run.p

      ## simple test - non-latest version
      - name: run-2
        uses: ./run
        with:
          version: 12.8.1
          license: ${{ secrets.PROGRESS_CFG_LICENSE }}
          startup-procedure: run/test/test_run.p

      ## set propath
      - name: run-3
        uses: ./run
        with:
          license: ${{ secrets.PROGRESS_CFG_LICENSE }}
          startup-procedure: run/test/search_ablunitcore.p
          propath: '$DLC/src/ablunit'

      ## additional parameters string
      - name: run-4A
        uses: ./run
        with:
          license: ${{ secrets.PROGRESS_CFG_LICENSE }}
          startup-procedure: run/test/log_message.p
          additional-parameters: "-clientlog client_log.log"
      - name: test-4A
        shell: bash
        run: |
          [ -f client_log.log ] || (echo "::error::expected client_log.log file to exist" && exit 1)
          grep "LONG LIVE LOG MANAGER!" client_log.log || (echo "::error::expected client_log.log to contain 'LONG LIVE LOG MANAGER', and it does not" && exit 1)

      ## additional parameters multiline
      - name: run-4B
        uses: ./run
        with:
          license: ${{ secrets.PROGRESS_CFG_LICENSE }}
          startup-procedure: run/test/log_message.p
          additional-parameters: |
            -clientlog client_log4B.log
            -logginglevel 4
      - name: test-4B
        shell: bash
        run: |
          [ -f client_log4B.log ] || (echo "::error::expected client_log4B.log file to exist" && exit 1)
          grep "LONG LIVE LOG MANAGER!" client_log4B.log || (echo "::error::expected client_log4B.log to contain 'LONG LIVE LOG MANAGER', and it does not" && exit 1)

      - name: pre-merge-validation
        shell: bash
        run: ./.github/workflows/pre_merge_validation.sh run
